# Generated by Django 5.2.5 on 2025-10-23 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(help_text='Name of the application', max_length=100)),
                ('username', models.CharField(help_text='Username for the application', max_length=100)),
                ('password', models.TextField(help_text='Encrypted password')),
                ('url', models.URLField(blank=True, help_text='Optional URL for the application', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['app_name', 'username'],
                'unique_together': {('user', 'app_name', 'username')},
            },
        ),
        migrations.CreateModel(
            name='UserAdditionalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text="User's first name", max_length=50)),
                ('last_name', models.CharField(help_text="User's last name", max_length=50)),
                ('mobile_number', models.CharField(help_text='13-digit mobile number (+91XXXXXXXXXX)', max_length=13)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Additional Data',
                'verbose_name_plural': 'User Additional Data',
            },
        ),
        migrations.CreateModel(
            name='AdditionalField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(help_text="Name of the custom field (e.g., 'mpin', 'profile_password')", max_length=50)),
                ('field_value', models.TextField(help_text='Encrypted value of the custom field')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('password_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_fields', to='passwords.passwordentry')),
            ],
            options={
                'unique_together': {('password_entry', 'field_name')},
            },
        ),
    ]
